#! /usr/bin/env node

const {
  getStdinAsJson, 
  getSourceConfig,
  getMergedPullRequests,
  convertToVersions
} = require('./common.js')

/** 
 * This is the main function
 * Read source configuration from stdin and then runs a graphQL query
 * to fetch MERGED or CLOSED pull requests
*/
async function check() {

  console.error("Checking for pull request events...")
  stdinJson = await getStdinAsJson()
  finalConfig = await getSourceConfig(stdinJson)
  pullRequests = await getMergedPullRequests(finalConfig)
  resultingVersions = convertToVersions(pullRequests)

  // if a version was given, concat the resulting versions
  // as per concourse resource spec
  if (finalConfig.version) {
    resultingVersions = [finalConfig.version].concat(resultingVersions)
  }


  // output the resulting versions to stdout for consumption by concourse
  console.log(JSON.stringify(resultingVersions))
}


check()